server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        svn:
#          uri:   #这里得使用http或https 目前集团不支持
#          username:
#          password:
#          default-label: /   # 默认trunk

        git:
          uri: https://github.com/SimonVampire/SpringCloudConfig/
          search-paths: respo
          username:
          password:
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
