server:
  port: 8888

spring:
  application:
    name: config-server
# 这里必须制定使用svn ,否则默认还是使用git
  profiles:
    active: subversion

  cloud:
    config:
      server:
        svn:
          uri: #svn://地址
          username: #用户名
          password: #密码
          default-label: /   # 默认trunk
          #默认在系统临时目录下面，需要调整一下避免临时文件被系统自动清理,如果更换SVN源 则需要删除basedir路径缓存数据
          basedir: data/cloudConfig


#        git:
#          uri: https://github.com/SimonVampire/SpringCloudConfig/
##          必须要有一个目录 否则读取不到配置,我这里的respo下不放任何东西 也可以读到外面的配置
#          search-paths: respo
#          username:
#          password:
#      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
