server:
  port: 8888

spring:
  application:
    name: config-server
# 这里必须制定使用svn ,否则默认还是使用git
  profiles:
    active: subversion

  cloud:
    config:
      server:
        svn:
          uri: # svn://SVN地址
          username: #用户名
          password: #密码
          default-label: /   # 默认trunk
#          basedir: data

#        git:
#          uri: https://github.com/SimonVampire/SpringCloudConfig/
##          必须要有一个目录 否则读取不到配置,我这里的respo下不放任何东西 也可以读到外面的配置
#          search-paths: respo
#          username:
#          password:
#      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
